In [1]:
import pandas as pd
import os

In [2]:
os.makedirs("output", exist_ok=True)

In [3]:
df = pd.read_csv("ecommerce_data.csv")

In [6]:
print("Dataset Shape:", df.shape)
print("\nFirst 5 Rows:")
df.head()

Dataset Shape: (20, 11)

First 5 Rows:

,Order_ID,Order_Date,Customer,City,Category,Product,Quantity,Unit_Price,Discount,Payment,Rating
0,1001,2026-01-05,Amit,Pune,Electronics,Laptop,1,55000,0.05,UPI,5
1,1002,2026-01-07,Sneha,Mumbai,Electronics,Headphones,2,2500,0.10,Card,4
2,1003,2026-01-12,Rahul,Delhi,Furniture,Chair,4,3500,0.05,Cash,4
3,1004,2026-01-18,Priya,Pune,Electronics,Keyboard,2,1800,0.00,UPI,5
4,1005,2026-02-03,Vikas,Mumbai,Electronics,Laptop,2,55000,0.08,Card,5

Data Cleaning

In [7]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [14]:
print("\nData Types:")
print(df.dtypes)

Data Types:
Order_ID               int64
Order_Date    datetime64[us]
Customer                 str
City                     str
Category                 str
Product                  str
Quantity               int64
Unit_Price             int64
Discount             float64
Payment                  str
Rating                 int64
dtype: object

In [15]:
print("\nMissing Values:")
print(df.isna().sum())

Missing Values:
Order_ID      0
Order_Date    0
Customer      0
City          0
Category      0
Product       0
Quantity      0
Unit_Price    0
Discount      0
Payment       0
Rating        0
dtype: int64

In [17]:
print("\nDuplicate Rows:")
print(df.duplicated().sum())

Duplicate Rows:
0

Calculate Revenue

In [19]:
# GROSS SALES
df["Gross_Sales"] = df["Quantity"] * df["Unit_Price"]

In [20]:
# DISCOUNT AMOUNT
df["Discount_Amount"] = df["Gross_Sales"] * df["Discount"]

In [21]:
# FINAL SALES
df["Net_Sales"] = df["Gross_Sales"] - df["Discount_Amount"]

In [22]:
df[
    [
        "Order_ID",
        "Product",
        "Quantity",
        "Gross_Sales",
        "Discount_Amount",
        "Net_Sales"
    ]
]

    Order_ID     Product  Quantity  Gross_Sales  Discount_Amount  Net_Sales
0       1001      Laptop         1        55000           2750.0    52250.0
1       1002  Headphones         2         5000            500.0     4500.0
2       1003       Chair         4        14000            700.0    13300.0
3       1004    Keyboard         2         3600              0.0     3600.0
4       1005      Laptop         2       110000           8800.0   101200.0
5       1006       Table         1         8500            850.0     7650.0
6       1007       Mouse         3         3600            180.0     3420.0
7       1008       Chair         6        21000           2100.0    18900.0
8       1009     Monitor         2        30000           1500.0    28500.0
9       1010      Laptop         1        55000              0.0    55000.0
10      1011       Table         2        17000            850.0    16150.0
11      1012       Mouse         4         4800            480.0     4320.0
12      1013    Keyboard         3         5400            270.0     5130.0
13      1014       Chair         2         7000              0.0     7000.0
14      1015     Monitor         2        30000           2400.0    27600.0
15      1016  Headphones         3         7500            375.0     7125.0
16      1017       Table         1         8500            850.0     7650.0
17      1018      Laptop         1        55000           2750.0    52250.0
18      1019       Chair         5        17500            875.0    16625.0
19      1020     Monitor         1        15000              0.0    15000.0

Create Time Features

In [26]:
df["Year"] = df["Order_Date"].dt.year
df["Month"] = df["Order_Date"].dt.month
df["Month_Name"] = df["Order_Date"].dt.month_name()
df["Quarter"] = df["Order_Date"].dt.quarter
df["Day_Name"] = df["Order_Date"].dt.day_name()

Basic Business KPIs

In [27]:
# TOTAL SALES
total_sales = df["Net_Sales"].sum()

In [28]:
# TOTAL ORDERS
total_order = df["Order_ID"].sum()

In [29]:
# TOTAL QUANTITY
total_quantity = df["Quantity"].sum()

In [30]:
# AVERAGE ORDER VALUE
average_order_value = df["Net_Sales"].mean()

In [31]:
# AVERAGE RATING
average_rating = df["Rating"].mean()

In [33]:
print("\n========== BUSINESS KPIs ==========")
print("Total Sales:", total_sales)
print("Total Orders:", total_order)
print("Total Quantity:", total_quantity)
print("Average Order Value:", average_order_value)
print("Average Rating:", average_rating)

========== BUSINESS KPIs ==========
Total Sales: 447170.0
Total Orders: 20210
Total Quantity: 48
Average Order Value: 22358.5
Average Rating: 4.25

City Analysis

In [34]:
city_report = (
    df.groupby("City")
    .agg(
        Total_Sales = ("Net_Sales", "sum"),
        Total_Orders = ("Order_ID", "nunique"),
        Total_Quantity = ("Quantity", "sum"),
        Average_Rating = ("Rating", "mean")
    )
    .reset_index()
    .sort_values("Total_Sales", ascending=False)
)

In [35]:
print("\n========== CITY REPORT ==========")
print(city_report)

========== CITY REPORT ==========
     City  Total_Sales  Total_Orders  Total_Quantity  Average_Rating
1  Mumbai     208770.0             6              17        4.166667
2    Pune     160070.0             8              13        4.500000
0   Delhi      78330.0             6              18        4.000000

In [36]:
city_report.to_csv(
    "output/city_sales_report.csv",
    index=False
)

Product Analysis

In [37]:
product_report = (
    df.groupby("Product")
    .agg(
        Total_Sales = ("Net_Sales", "sum"),
        Total_Orders = ("Order_ID", "nunique"),
        Total_Quantity = ("Quantity", "sum"),
        Average_Rating = ("Rating", "mean")
    )
    .reset_index()
    .sort_values("Total_Sales", ascending=False)
)

In [41]:
print("\n========== PRODUCT REPORT ==========")
print(product_report)

========== PRODUCT REPORT ==========
      Product  Total_Sales  Total_Orders  Total_Quantity  Average_Rating
3      Laptop     260700.0             4               5        5.000000
4     Monitor      71100.0             3               5        4.666667
0       Chair      55825.0             4              17        4.000000
6       Table      31450.0             3               4        3.666667
1  Headphones      11625.0             2               5        4.000000
2    Keyboard       8730.0             2               5        4.000000
5       Mouse       7740.0             2               7        4.000000

In [42]:
product_report.to_csv(
    "output/product_sales_report.csv",
    index=False
)

Category Analysis

In [40]:
category_report = (
    df.groupby("Category")
    .agg(
        Total_Sales = ("Net_Sales", "sum"),
        Total_Orders = ("Order_ID", "nunique"),
        Total_Quantity = ("Quantity", "sum"),
        Average_Rating = ("Rating", "mean")
    )
    .reset_index()
    .sort_values("Total_Sales", ascending=False)
)

In [43]:
print("\n========== CATEGORY REPORT ==========")
print(category_report)

========== CATEGORY REPORT ==========
      Category  Total_Sales  Total_Orders  Total_Quantity  Average_Rating
0  Electronics     359895.0            13              27        4.461538
1    Furniture      87275.0             7              21        3.857143

In [44]:
category_report.to_csv(
    "output/category_sales_report.csv",
    index=False
)

Monthly Sales

In [45]:
monthly_report = (
    df.groupby(["Year", "Month", "Month_Name"])
      .agg(
          Total_Sales=("Net_Sales", "sum"),
          Total_Orders=("Order_ID", "nunique"),
          Total_Quantity=("Quantity", "sum")
      )
      .reset_index()
      .sort_values(["Year", "Month"])
)

In [46]:
print("\n========== MONTHLY REPORT ==========")
print(monthly_report)

========== MONTHLY REPORT ==========
   Year  Month Month_Name  Total_Sales  Total_Orders  Total_Quantity
0  2026      1    January      73650.0             4               9
1  2026      2   February     131170.0             4              12
2  2026      3      March     103970.0             4               9
3  2026      4      April      39730.0             3               7
4  2026      5        May      67025.0             3               5
5  2026      6       June      31625.0             2               6

In [47]:
monthly_report.to_csv(
    "output/monthly_sales_report.csv",
    index=False
)

Payment Analysis

In [48]:
payment_report = (
    df.groupby("Payment")
      .agg(
          Total_Sales=("Net_Sales", "sum"),
          Total_Orders=("Order_ID", "nunique")
      )
      .reset_index()
      .sort_values("Total_Sales", ascending=False)
)

In [49]:
print("\n========== PAYMENT REPORT ==========")
print(payment_report)

========== PAYMENT REPORT ==========
  Payment  Total_Sales  Total_Orders
0    Card     278770.0             8
2     UPI     138900.0             8
1    Cash      29500.0             4

In [50]:
payment_report.to_csv(
    "output/payment_report.csv",
    index=False
)

Find Top Performers

In [51]:
top_product = (
    product_report
    .sort_values("Total_Sales", ascending=False)
    .iloc[0]
)

print("\nTop Product:")
print(top_product)

Top Product:
Product             Laptop
Total_Sales       260700.0
Total_Orders             4
Total_Quantity           5
Average_Rating         5.0
Name: 3, dtype: object

In [52]:
top_city = city_report.iloc[0]

print("\nTop City:")
print(top_city)

Top City:
City                Mumbai
Total_Sales       208770.0
Total_Orders             6
Total_Quantity          17
Average_Rating    4.166667
Name: 1, dtype: object

In [53]:
top_category = category_report.iloc[0]

print("\nTop Category:")
print(top_category)

Top Category:
Category          Electronics
Total_Sales          359895.0
Total_Orders               13
Total_Quantity             27
Average_Rating       4.461538
Name: 0, dtype: object

Ranking

In [54]:
product_report["Sales_Rank"] = (
    product_report["Total_Sales"]
    .rank(ascending=False, method="dense")
    .astype(int)
)

In [55]:
product_report = product_report.sort_values("Sales_Rank")

Customer Analysis

In [56]:
customer_report = (
    df.groupby("Customer")
      .agg(
          Total_Sales=("Net_Sales", "sum"),
          Total_Orders=("Order_ID", "nunique"),
          Total_Quantity=("Quantity", "sum"),
          Average_Order_Value=("Net_Sales", "mean")
      )
      .reset_index()
      .sort_values("Total_Sales", ascending=False)
)

In [57]:
customer_report.to_csv(
    "output/customer_sales_report.csv",
    index=False
)

Customer Segmentation

In [58]:
customer_report["Customer_Segment"] = pd.cut(
    customer_report["Total_Sales"],
    bins=[0, 20000, 50000, float("inf")],
    labels=["Low Value", "Medium Value", "High Value"]
)

In [59]:
print("\nCustomer Segments:")
print(
    customer_report[
        ["Customer", "Total_Sales", "Customer_Segment"]
    ]
)

Customer Segments:
  Customer  Total_Sales Customer_Segment
9    Vikas     128800.0       High Value
2    Kiran      71150.0       High Value
7    Rohit      70000.0       High Value
0     Amit      68400.0       High Value
6     Riya      45125.0     Medium Value
5    Rahul      18430.0        Low Value
3     Neha      14775.0        Low Value
1    Arjun      11070.0        Low Value
4    Priya      10600.0        Low Value
8    Sneha       8820.0        Low Value

Category × City Analysis

In [60]:
category_city = pd.pivot_table(
    df,
    index="Category",
    columns="City",
    values="Net_Sales",
    aggfunc="sum",
    fill_value=0,
    margins=True
)

In [61]:
print("\n========== CATEGORY × CITY ==========")
print(category_city)

========== CATEGORY × CITY ==========
City           Delhi    Mumbai      Pune       All
Category
Electronics  40755.0  189870.0  129270.0  359895.0
Furniture    37575.0   18900.0   30800.0   87275.0
All          78330.0  208770.0  160070.0  447170.0

In [62]:
category_city.to_csv(
    "output/category_city_matrix.csv"
)

Create an Executive Summary

In [64]:
print("\n" + "=" * 50)
print("        E-COMMERCE EXECUTIVE SUMMARY")
print("=" * 50)

print(f"Total Sales       : ₹{total_sales:,.2f}")
print(f"Total Orders      : {total_order}")
print(f"Total Quantity    : {total_quantity}")
print(f"Average Order     : ₹{average_order_value:,.2f}")
print(f"Average Rating    : {average_rating:.2f}")

print(f"\nTop Product       : {top_product['Product']}")
print(f"Top City          : {top_city['City']}")
print(f"Top Category      : {top_category['Category']}")

print("=" * 50)

==================================================
        E-COMMERCE EXECUTIVE SUMMARY
==================================================
Total Sales       : ₹447,170.00
Total Orders      : 20210
Total Quantity    : 48
Average Order     : ₹22,358.50
Average Rating    : 4.25

Top Product       : Laptop
Top City          : Mumbai
Top Category      : Electronics
==================================================